android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
org.gradle.daemon=false

org.gradle.jvmargs=-Xmx512m -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m

org.gradle.caching=false
org.gradle.vfs.watch=false
